{{- $httproute := (.Values.httproute | default dict) }}
{{- if ($httproute.enabled | default false) }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: loki-frontend
spec:
  parentRefs:
    - name: {{ $httproute.gateway_name | default "istio-gateway" }}
      namespace: {{ $httproute.gateway_namespace | default "istio-ingress" }}
      sectionName: https
  hostnames:
    - {{ $httproute.host | quote }}
  rules:
    - backendRefs:
        - name: {{ $httproute.service_name | default "loki-query-frontend" }}
          port: 3100
{{- end }}
